[package]
name = "c2-gcd"
version = "0.1.0"
authors = ["Igor Gentil <igor.lg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
